language: csharp
solution: "./Facebook.ApiClient/Facebook.ApiClient.sln"
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0 
script:
- dotnet restore ./Facebook.ApiClient/Facebook.ApiClient/Facebook.ApiClient.csproj
- dotnet build ./Facebook.ApiClient/Facebook.ApiClient/Facebook.ApiClient.csproj -c Release -v normal -f netstandard2.0 --force
